// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPtnBurdAOYom5zmrQVzZgL9kozumvKIA',
    appId: '1:635288509996:web:c313b9d50382bb16d2fb89',
    messagingSenderId: '635288509996',
    projectId: 'chat-app-5ad8b',
    authDomain: 'chat-app-5ad8b.firebaseapp.com',
    storageBucket: 'chat-app-5ad8b.appspot.com',
    measurementId: 'G-HV1N8J9HW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArMVCKIg6pWfmh4vJNtrYcE0uE5Y2TwVw',
    appId: '1:635288509996:android:994644206b3e34c9d2fb89',
    messagingSenderId: '635288509996',
    projectId: 'chat-app-5ad8b',
    storageBucket: 'chat-app-5ad8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jcuDlhuWQzNSTJToe-Ii0KgMVRArD6c',
    appId: '1:635288509996:ios:2f0162f9edb3ba5ed2fb89',
    messagingSenderId: '635288509996',
    projectId: 'chat-app-5ad8b',
    storageBucket: 'chat-app-5ad8b.appspot.com',
    iosClientId: '635288509996-us4joveipmnqem48sr0dsnv36aahib58.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jcuDlhuWQzNSTJToe-Ii0KgMVRArD6c',
    appId: '1:635288509996:ios:0cc0ce33ac10b2d1d2fb89',
    messagingSenderId: '635288509996',
    projectId: 'chat-app-5ad8b',
    storageBucket: 'chat-app-5ad8b.appspot.com',
    iosClientId: '635288509996-5tg28fhucqmkelol70f3idgvkb97ic0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
